Perso initialisation_perso();
void aff_matrice(int mat[DTAILLE][DTAILLE]);
void aff_vision(int mat[DTAILLE][DTAILLE],int xp,int yp);
void tombe_vide(Perso* ptombe);
Perso remplisagecoffre();
void sommedinventaire(Perso* pa,Perso* pc);
void affichage_inventaire(Perso* pperso);
void affichage(Perso* pperso,int matrice[DTAILLE][DTAILLE]);
Position_Autour pautour(Perso a);
void creation_tombe(Perso* pperso,Perso* ptombe,int matrice[DTAILLE][DTAILLE]);
void prise_objet_main(Perso* pperso,short b,int matrice[DTAILLE][DTAILLE]);
void utilisation(Perso* pperso,int matrice[DTAILLE][DTAILLE]);
void ouverture_coffre(Perso* pperso);
void ouverture_tombe(Perso* pperso,Perso* ptombe);
void verification_objet_statique(Perso* pperso,Perso* ptombe,int matrice[DTAILLE][DTAILLE],Position_Autour alpha);
int mort_monstre(int matrice[DTAILLE][DTAILLE],Salle* donj,Perso* pperso,int i);
void attaque(Perso* pperso,int matrice[DTAILLE][DTAILLE],Position_Autour alpha,Salle* donj);
int mouvementperso(int m,Perso* pperso,int matrice[DTAILLE][DTAILLE],Salle* donj,int* nbS,int nbSmax,int* nbspotentielle,int* nbcaillou,int nbstot,int* bobby_la);
short queltouche(char a[256],int matrice[DTAILLE][DTAILLE]);
void actionafaire(short b, Perso* pperso,Perso*ptombe,int matrice[DTAILLE][DTAILLE],Salle* donj,int* nbS,int nbSmax,int* nbspotentielle,int* nbcaillou,int nbstot,int* bobby_la);
void enchainement(Perso* pperso,int matrice[DTAILLE][DTAILLE],Salle* donj,int* nbS,int nbSmax,int* nbspotentielle,int* nbcaillou,int nbstot,int* bobby_la,Perso* ptombe);
int num_s_perso(Salle* donj,Perso* j,int nbs);
